import pandas as pd

print("=" * 80)
print("1. CARDIAC FAILURE PROCESSED")
print("=" * 80)
df1 = pd.read_csv(r'Data\Cardiac Failure\cardiac_failure_processed.csv')
print(f"Shape: {df1.shape}")
print(f"Columns: {list(df1.columns)}")
print("\nFirst 2 rows:")
print(df1.head(2))
print("\nData types:")
print(df1.dtypes)

print("\n" + "=" * 80)
print("2. CARDIO BASE")
print("=" * 80)
df2 = pd.read_csv(r'Data\Cardiac Failure\cardio_base.csv', sep=';')
print(f"Shape: {df2.shape}")
print(f"Columns: {list(df2.columns)}")
print("\nFirst 2 rows:")
print(df2.head(2))

print("\n" + "=" * 80)
print("3. HEART ATTACK")
print("=" * 80)
df3 = pd.read_csv(r'Data\Heart Attack\heart_processed.csv')
print(f"Shape: {df3.shape}")
print(f"Columns: {list(df3.columns)}")
print("\nFirst 2 rows:")
print(df3.head(2))
print("\nData types:")
print(df3.dtypes)

print("\n" + "=" * 80)
print("4. ECG TIMESERIES (first 1000 rows sample)")
print("=" * 80)
df4 = pd.read_csv(r'Data\ECG Timeseries\ecg_timeseries.csv', nrows=1000)
print(f"Shape (sample): {df4.shape}")
print(f"Columns: {list(df4.columns)}")
print("\nFirst 2 rows:")
print(df4.head(2))
